### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for BertForSequenceClassification

### ISSUE THREAD

**Issue by KnutJaegersberg** [oliverguhr/german-sentiment-lib#1]
downloading the model worked fine, but I cant use it. Whats up here?

>>> import germansentiment
>>> from germansentiment import SentimentModel
>>> 
>>> model = SentimentModel()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/knut/.local/lib/python3.8/site-packages/germansentiment/sentimentmodel.py", line 8, in __init__
    self.model = AutoModelForSequenceClassification.from_pretrained(model_name)
  File "/usr/lib/python3.8/site-packages/transformers/modeling_auto.py", line 807, in from_pretrained
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, config=config, **kwargs)
  File "/usr/lib/python3.8/site-packages/transformers/modeling_utils.py", line 556, in from_pretrained
    raise RuntimeError(
RuntimeError: Error(s) in loading state_dict for BertForSequenceClassification:
        size mismatch for classifier.weight: copying a param with shape torch.Size([3, 768]) from checkpoint, the shape in current model is torch.Size([2, 768]).
        size mismatch for classifier.bias: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([2]).

**Comment by oliverguhr** [comment]
Hi Knut,
I tried to reproduce this error, but it works fine for me. Could you update the dependencies and test this again?

```
pip3 install  --upgrade torch
pip3 install  --upgrade transformers
pip3 install  --upgrade germansentiment
```

**Comment by oliverguhr** [comment]
I'll close this issue for now. If you have any questions, feel free to reopen the issue.

**Comment by johann-petrak** [comment]
I am getting the same error though this has worked in 2020-11 for me with exactly the same code (however it seems the model got re-downloaded when I tried now).

My torch version is 1.6.0+cu101, my transformers version is 2.3.0
