### ISSUE TITLE
how to fine tune the model based on our ground truth

### ISSUE THREAD

**Issue by bpfrd** [oliverguhr/german-sentiment-lib#11]
Hi,

thank you very much for your interesting code. I would like to know how we can fine tune the model based on our ground truth?

Best 
B

**Comment by oliverguhr** [comment]
Hi @bpfrd,
here is a tutorial on how this works: https://huggingface.co/docs/transformers/training

Its even the same task - you just need to load you data and use "oliverguhr/german-sentiment-bert" as a your model.
