### ISSUE TITLE
Difference of PyPI package and Huggingface model

### ISSUE THREAD

**Issue by andyherzberg** [oliverguhr/german-sentiment-lib#12]
Hello,
Thanks for sharing the great sentiment model and the Python library. I am using it in one of my projects and I wanted to ask you about the difference of the model of the germansentiment library versus the huggingface model as I realized some differences in the score output. The following code brings up a 'positive' label (score prob of 0.92) with the germansentiment library while the huggingface model brings up a 'negative' label (score prob of 0.95). 
Is this just because of the training data you were using to create the model or is there any other difference one should be aware of?
Many thanks and best regards, 
Andy 

PS: This is the code I am using:
```
from germansentiment import SentimentModel
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import pipeline

text = "Servus." 

# PyPI germansentiment 1.1.0
model = SentimentModel()
texts = [text]
result = model.predict_sentiment(texts, output_probabilities = True)[1][0]

# Huggingface oliverguhr/german-sentiment-bert
model_name = "oliverguhr/german-sentiment-bert"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)
classifier = pipeline(task="sentiment-analysis", model=model_name, tokenizer=tokenizer)
result2 = classifier([text])

print('PyPI germansentiment 1.1.0', '\n', result, '\n\n', 'Huggingface oliverguhr/german-sentiment-bert', '\n', result2)
```

**Comment by oliverguhr** [comment]
Hi @andyherzberg,
the germansentiment lib uses the same preprocessing that I used during the training of the model. The pipeline code does not use any preprocessing, that is the reason why you get different results. 

Some people reported that the pipeline version works better for them. However, I would be careful since this will feed unseen data into the model which can lead to unstable behavior. 

Best
Oliver

**Comment by andyherzberg** [comment]
Hi @oliverguhr, 
Thanks for the explanation. You are right it totally makes sense to normalize the text the way you do before putting this into the pipeline! But if the underlying model is the same I am still confused why my toy example with the string "Servus." brings up a positive and a negative label for the library and the hf pipeline. The normalization steps don't seem to affect the string as far as I could see bychecking the code here [sentimentmodel.py](https://github.com/oliverguhr/german-sentiment-lib/blob/master/germansentiment/sentimentmodel.py). 
Thanks again! Andy

**Comment by oliverguhr** [comment]
"Servus." contains upper case and punctuation which both get removed by the preprocessing.

If you put "servus" in the Pipeline the results should be identical.

**Comment by andyherzberg** [comment]
My bad, sorry! You are right! 💯 After removing punctuation and turning to lowercase the results are identical. Thank you for taking the time to explain this! 
Best regards!
