### ISSUE TITLE
Links in dataset table points to this repository

### ISSUE THREAD

**Issue by micw** [oliverguhr/german-sentiment-lib#2]
Hello Oliver,

in the table "datasets" (in README.md), some links point to https://github.com/oliverguhr/german-sentiment rather than the actual datasets.

Best regards,
Michael.

**Comment by oliverguhr** [comment]
Hi Michael,
thank you for your feedback. Its a bit confusing, since I trained the model on serval datasets. Probably I should refer just to the "german-sentiment" repository since this explains the model, data and process in more detail. What do you think?
