### ISSUE TITLE
Warning from transformers lib

### ISSUE THREAD

**Issue by micw** [oliverguhr/german-sentiment-lib#3]
When I use the library (as in the example), I always get this warning:

transformers/tokenization_utils_base.py:2136: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).

Environment:
- ArchLinux
- Python 3.9
- Transformers 4.0.0

**Comment by oliverguhr** [comment]
Thanks for the bug report. I fixed the issue and created a new release 1.0.4 - it's available on pypi.
