### ISSUE TITLE
Results depend on used PyTorch version

### ISSUE THREAD

**Issue by poke1024** [oliverguhr/german-sentiment-lib#5]
Hello there.

We ran some texts through this nice library and found that the results are different when using PyTorch 1.7.1 (CPU) and PyTorch >= 1.8.0 (CPU). We believe this might be a problem in `torch` and/or `tranformers`, but start here with reporting the finding.

For our test code, see the attached `test_case_code.zip`. For the results, see the attach `test_case_results.zip`. There, note the following differences:

* `test_case_results/out-torch-1.7.1/results_news_full.txt` differs from `test_case_results/out-torch-1.8.0/results_news_full.txt`, even though the same code is run with the same data
* `test_case_results/out-torch-1.7.1/results_news_part.txt` differs from `test_case_results/out-torch-1.8.0/results_news_part.txt`, even though the same code is run with the same data

Strangely, when we use the example sentences from the `germansentiment'`s own test case, the results do not differ and both work as expected (compare `out-torch-1.7.1/results_guhr.txt` and `out-torch-1.8.0/results_guhr.txt`), which makes this finding even more tricky.

Attached in the `debug_` files (inside `test_case_results`) are some of the internal outputs of the model.

[test_case_results.zip](https://github.com/oliverguhr/german-sentiment-lib/files/6325967/test_case_results.zip)

[test_case_code.zip](https://github.com/oliverguhr/german-sentiment-lib/files/6325953/test_case_code.zip)

**Comment by oliverguhr** [comment]
I trained the model in 2019, since then some things might have changed in the library (transformers and torch). So it's possible that different torch versions lead to different results, altho that should not be the case. I try to reproduce that and write you back.

**Comment by oliverguhr** [comment]
If you use Huggingface Model Hub with your examples, the results are the same as with torch 1.7.1. 

[Jeder Tag der Verzögerung richtet neues Unheil an.](https://huggingface.co/oliverguhr/german-sentiment-bert?text=jeder+tag+der+verz%C3%B6gerung+richtet+neues+unheil+an) = Neutral 
[Ausgesprochen schwach lagen Motoren Deutz, die 2% verloren.](https://huggingface.co/oliverguhr/german-sentiment-bert?text=ausgesprochen+schwach+lagen+motoren+deutz+die+2+verloren) = Neutral
[Mark für 100 Gmk.](https://huggingface.co/oliverguhr/german-sentiment-bert?text=mark+f%C3%BCr+eins+null+null+gmk) = Negative

**Comment by oliverguhr** [comment]
I was able to reproduce the issue that you described with pytorch 1.8.0.  Hoever, with pytorch 1.8.1 the are same results as with torch 1.7.1. **It looks like there is an issue with pytorch 1.8.0 than can be solved by upgrading to 1.8.1**.

**Comment by poke1024** [comment]
Results with pytorch 1.8.1 are indeed identical to those with 1.7.1 (also see attachment).

https://github.com/pytorch/pytorch/releases lists a number of bug fixes - none of them sounds crucial, but obviously one of them fixed this.

Closing this.

Thanks for your investigation into this!

[out-torch-1.8.1+cu102.zip](https://github.com/oliverguhr/german-sentiment-lib/files/6336200/out-torch-1.8.1%2Bcu102.zip)

**Comment by oliverguhr** [comment]
Indeed, that is a very strange issue. Just write to me, if you have any other questions.
