### ISSUE TITLE
Results depend on batch structure/other texts

### ISSUE THREAD

**Issue by poke1024** [oliverguhr/german-sentiment-lib#6]
Results change depending on whether data is fed as a single sentence or as a batch. This might be a bug in `torch` and/or `transformers`, however we start by reporting it here.

Expected behavior: `test_case_results/out-torch-1.8.0/results_news_full.txt` and `results_news_part.txt` should yield the same results.

Actual behavior: Results are different.

Further details: In the `results_news_full` case, we feed `n` texts to `predict` and then print out a selection of texts. In the `results_news_part` case, we only feed the selected texts to `predict`. The results vary, which means the result for a single texts depends on the accompanying  texts with which `predict` is called. As far as we understand it, this is not expected.

[test_case_results.zip](https://github.com/oliverguhr/german-sentiment-lib/files/6326012/test_case_results.zip)
[test_case_code.zip](https://github.com/oliverguhr/german-sentiment-lib/files/6326013/test_case_code.zip)

**Comment by oliverguhr** [comment]
I suspect that this is due to the same error as #https://github.com/oliverguhr/german-sentiment-lib/issues/5#issuecomment-822421024  
Can you please try to upgrade your pytorch version?

**Comment by poke1024** [comment]
Yes, indeed, with pytorch 1.8.1 the full and partial results are identical again, as with pytorch 1.7.1. Closing this.
